apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default

  source:
    path: test
    repoURL: 'https://github.com/venu67776/Argo-cd.git'
    targetRevision: HEAD
  destination:
    namespace: myapp
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true